# Generated by Django 3.1.7 on 2021-02-21 07:59

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('QueApp', '0011_auto_20210221_0759'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardModel',
            fields=[
            ],
            options={
                'verbose_name': 'Question Statistic',
                'verbose_name_plural': 'Questions Statistic',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('QueApp.questionsmodel',),
        ),
    ]
