# Generated by Django 3.1.4 on 2021-01-05 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question', models.CharField(max_length=200)),
                ('CorrectAnswer', models.IntegerField()),
                ('Answer1', models.CharField(default=None, max_length=50)),
                ('Answer2', models.CharField(default=None, max_length=50)),
                ('Answer3', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('Answer4', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('Answer5', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('Answer6', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('Answer7', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('Answer8', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('Answer9', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('Answer10', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('Answer11', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('Answer12', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('Answer13', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('Answer14', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('Answer15', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('Answer16', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('Answer17', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('Answer18', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('Answer19', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('Answer20', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('Answer21', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('Answer22', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('Answer23', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('Answer24', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('Answer25', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('Answer26', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('Answer27', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('Answer28', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('Answer29', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('Answer30', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('Answer31', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('Answer32', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('Answer33', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('Answer34', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('Answer35', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('Answer36', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('Answer37', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('Answer38', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('Answer39', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('Answer40', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('Answer41', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('Answer42', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('Answer43', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('Answer44', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('Answer45', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('Answer46', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('Answer47', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('Answer48', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('Answer49', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('Answer50', models.CharField(blank=True, default=None, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AnswersModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Answer', models.CharField(max_length=200)),
                ('OrderNum', models.IntegerField()),
                ('Question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QueApp.questionsmodel')),
            ],
        ),
    ]
