# Generated by Django 3.1.4 on 2021-01-05 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QueApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answersmodel',
            name='Question',
        ),
        migrations.AddField(
            model_name='questionsmodel',
            name='answer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='QueApp.answersmodel'),
            preserve_default=False,
        ),
    ]
