# Generated by Django 3.1.4 on 2021-01-06 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QueApp', '0004_auto_20210105_2040'),
    ]

    operations = [
        migrations.CreateModel(
            name='PushNotificationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PushMsg', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='answersmodel',
            name='Question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Answers', to='QueApp.questionsmodel'),
        ),
    ]
