# Generated by Django 3.1.5 on 2021-01-16 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QueApp', '0005_auto_20210106_1516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answersmodel',
            name='OrderNum',
        ),
        migrations.CreateModel(
            name='UsersAnswerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RegistrationID', models.CharField(max_length=200)),
                ('Answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UsersAnswer', to='QueApp.answersmodel')),
            ],
        ),
    ]
