# Generated by Django 3.1.5 on 2021-01-28 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QueApp', '0006_auto_20210116_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersanswermodel',
            name='APNSDevice',
            field=models.CharField(default='no name', max_length=200),
        ),
    ]
