# Generated by Django 3.1.5 on 2021-01-30 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QueApp', '0007_usersanswermodel_apnsdevice'),
    ]

    operations = [
        migrations.AddField(
            model_name='pushnotificationmodel',
            name='PushTitle',
            field=models.CharField(default='', max_length=200),
        ),
    ]
