# Generated by Django 3.1.5 on 2021-02-05 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QueApp', '0008_pushnotificationmodel_pushtitle'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answersmodel',
            options={'verbose_name_plural': 'Answers'},
        ),
        migrations.AlterModelOptions(
            name='pushnotificationmodel',
            options={'verbose_name_plural': 'Push Notifictions Message'},
        ),
        migrations.AlterModelOptions(
            name='questionsmodel',
            options={'verbose_name_plural': 'Questions'},
        ),
        migrations.AlterModelOptions(
            name='usersanswermodel',
            options={'verbose_name_plural': 'Users Answer'},
        ),
        migrations.AlterField(
            model_name='pushnotificationmodel',
            name='PushMsg',
            field=models.CharField(default='', max_length=200),
        ),
    ]
