# Generated by Django 3.1.5 on 2021-02-10 08:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('QueApp', '0009_auto_20210205_1020'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardModel',
            fields=[
            ],
            options={
                'verbose_name': 'Main Dashboard',
                'verbose_name_plural': 'Main Dashboards',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('QueApp.questionsmodel',),
        ),
        migrations.AddField(
            model_name='questionsmodel',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pushnotificationmodel',
            name='PushTitle',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
