# Generated by Django 3.1.7 on 2021-02-21 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QueApp', '0010_auto_20210210_0842'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DashboardModel',
        ),
        migrations.AlterModelOptions(
            name='pushnotificationmodel',
            options={'verbose_name': 'Push Notifiction', 'verbose_name_plural': 'Push Notifictions Message'},
        ),
        migrations.AlterField(
            model_name='answersmodel',
            name='Question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='QuestionAnswer', to='QueApp.questionsmodel'),
        ),
    ]
